import React, { useState, useEffect, useRef } from "react";
import { 
  Sparkles, 
  Heart, 
  Scale, 
  User, 
  Compass, 
  BookOpen, 
  Smile, 
  MessageSquare, 
  Apple, 
  Send, 
  Play, 
  HelpCircle, 
  Calendar, 
  Activity, 
  ChevronRight, 
  Utensils, 
  Flame, 
  CheckCircle, 
  RefreshCw,
  Lightbulb,
  MapPin,
  Clock,
  Video
} from "lucide-react";
import { computeNutriGenomicArchetype, WELLNESS_VIDEOS, QUICK_DOUBTS, SAMPLE_MEAL_PLANS } from "./data";
import { PhysicalProfile, ChatMessage, JournalLog } from "./types";

// Import beautiful asset paths generated by the image helper
import coachSamImg from "./assets/images/coach_sam_1781414139228.jpg";
import nutriBowlImg from "./assets/images/vibrant_nutri_bowl_1781414156237.jpg";

export default function App() {
  // 1. Initial State for User Profile
  const [profile, setProfile] = useState<PhysicalProfile>({
    weight: 68,
    height: 165,
    age: 27,
    biologicalSex: "female",
    activity: "moderate",
    goal: "balanced",
    dietType: "flexible",
  });

  // Derived state: compute archetype on-the-fly or base it on trigger
  const [archetype, setArchetype] = useState(() => computeNutriGenomicArchetype(profile));
  const [isUpdating, setIsUpdating] = useState(false);

  // 2. Chat history with Sam (preloaded with deep friendly warmth and reassurance)
  const [chatHistory, setChatHistory] = useState<ChatMessage[]>([
    {
      id: "init-1",
      role: "model",
      text: "Hey love! I'm Sam, your personal coach and best friend. 🌸 First off: take a deep breath. No scales are going to define us here, and there is ZERO judgment. Whatever you did yesterday, you're here today, and that's beautiful! Let's enter your biometrics so we can calculate your genuine body archetype and design a colorful, delicious plate customized just for you. How are you feeling today?",
      timestamp: "Just now"
    }
  ]);
  const [userInput, setUserInput] = useState("");
  const [isChatLoading, setIsChatLoading] = useState(false);

  // Ref for chat auto-scroll
  const chatEndRef = useRef<HTMLDivElement>(null);

  // 3. User Journal logs state
  const [journalLogs, setJournalLogs] = useState<JournalLog[]>([
    {
      id: "j-1",
      date: "Today",
      feeling: "radiant",
      note: "Cooked a fresh avocado scramble and felt so energized today. Glad Sam is here to support me!"
    }
  ]);
  const [newJournalNote, setNewJournalNote] = useState("");
  const [selectedFeeling, setSelectedFeeling] = useState<"radiant" | "cozy" | "bloated" | "tired" | "unstoppable" | "content">("radiant");

  // 4. Live media modal for video streams
  const [selectedVideoUrl, setSelectedVideoUrl] = useState<string | null>(null);

  // Scroll to bottom of chat
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [chatHistory, isChatLoading]);

  // Recalculate Archetype easily
  const handleUpdateProfile = (e: React.FormEvent) => {
    e.preventDefault();
    setIsUpdating(true);
    
    // Validate and clamp age strictly to healthy limits (12 to 110) on unlock/submission
    const validatedAge = Math.min(110, Math.max(12, profile.age || 27));
    const validatedProfile = {
      ...profile,
      age: validatedAge
    };
    setProfile(validatedProfile);

    setTimeout(() => {
      const computed = computeNutriGenomicArchetype(validatedProfile);
      setArchetype(computed);
      setIsUpdating(false);

      // Programmatically add a friendly notification chat message from Sam
      const updateAlert: ChatMessage = {
        id: `sys-${Date.now()}`,
        role: "model",
        text: `Oh my gosh, I just analyzed your updated stats! your body maps beautifully to the ${computed.name} archetype. 🧬 I've prepared a custom meal plan optimized specifically for your height/weight. Let me know if you want me to translate the macros or tweak anything for your absolute favorite cravings today!`,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };
      setChatHistory(prev => [...prev, updateAlert]);
    }, 700);
  };

  // Chat message submission
  const handleSendMessage = async (textToSend?: string) => {
    const rawMsg = textToSend || userInput;
    if (!rawMsg.trim()) return;

    const userMessage: ChatMessage = {
      id: `usr-${Date.now()}`,
      role: "user",
      text: rawMsg,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    setChatHistory(prev => [...prev, userMessage]);
    if (!textToSend) setUserInput("");
    setIsChatLoading(true);

    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: rawMsg,
          history: chatHistory.map(c => ({ role: c.role, text: c.text })),
          profile: {
            weight: profile.weight,
            height: profile.height,
            age: profile.age,
            goal: profile.goal,
            dietType: profile.dietType,
            activity: profile.activity,
            archetypedName: archetype.name,
            archetypedCode: archetype.code
          }
        })
      });

      if (!response.ok) {
        throw new Error("Sam got a bit disconnected.");
      }

      const data = await response.json();
      const modelMessage: ChatMessage = {
        id: `sam-${Date.now()}`,
        role: "model",
        text: data.reply,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };

      setChatHistory(prev => [...prev, modelMessage]);
    } catch (err: any) {
      const errorMessage: ChatMessage = {
        id: `err-${Date.now()}`,
        role: "model",
        text: "I'm right here with you! There was a tiny network hiccup, but don't worry. Ask me again or tell me how else I can support you right now, honey!",
        timestamp: "Now"
      };
      setChatHistory(prev => [...prev, errorMessage]);
    } finally {
      setIsChatLoading(false);
    }
  };

  // Add Journal Entry
  const handleAddJournal = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newJournalNote.trim()) return;

    const entry: JournalLog = {
      id: `journal-${Date.now()}`,
      date: "Just now",
      feeling: selectedFeeling,
      note: newJournalNote
    };

    setJournalLogs([entry, ...journalLogs]);

    // Send the journal update to Sam automatically to trigger a sweet response
    const customChatAlert = `Hey Sam, I just logged a journal note. I am feeling "${selectedFeeling}". Here is my journal: "${newJournalNote}". Talk to me and keep me grounded.`;
    handleSendMessage(customChatAlert);

    setNewJournalNote("");
  };

  // Clear or reset profile parameters back to a warm radiant baseline
  const handleResetProfile = () => {
    setProfile({
      weight: 68,
      height: 165,
      age: 27,
      biologicalSex: "female",
      activity: "moderate",
      goal: "balanced",
      dietType: "flexible",
    });
    setArchetype(computeNutriGenomicArchetype({
      weight: 68,
      height: 165,
      age: 27,
      activity: "moderate",
      goal: "balanced",
      dietType: "flexible",
    }));
  };

  return (
    <div className="min-h-screen bg-gradient-to-tr from-[#FFF7ED] via-[#FFF1F2] to-[#FFFBEB] font-sans text-neutral-800 transition-all duration-300">
      
      {/* 1. Header & Aesthetic Brand Bar */}
      <header className="sticky top-0 z-40 bg-white/70 backdrop-blur-md border-b border-rose-100/50 shadow-xs px-4 py-3 sm:px-8 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="bg-gradient-to-r from-rose-400 to-amber-400 p-2 rounded-full shadow-md text-white animate-pulse">
            <Heart className="w-5 h-5 fill-current" />
          </div>
          <div>
            <h1 className="font-display font-extrabold text-xl sm:text-2xl tracking-tight text-neutral-800 flex items-center gap-2">
              Bloom <span className="text-transparent bg-clip-text bg-gradient-to-r from-rose-500 to-amber-500">with Sam</span>
            </h1>
            <p className="text-xs text-neutral-500 font-medium italic">Your guilt-free, loving metabolic sanctuary</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <div className="hidden md:flex flex-col text-right">
            <span className="text-xs font-semibold text-rose-500 bg-rose-50 px-2 py-0.5 rounded-full inline-block self-end">
              Active Genomics Spark
            </span>
            <span className="text-[10px] text-neutral-400 font-mono">Profile ID: G-ARCH-ACTIVE</span>
          </div>
        </div>
      </header>

      {/* Hero Welcome banner with Coach Sam & bright color aesthetics */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-6">
        <div className="relative overflow-hidden bg-gradient-to-r from-amber-100 via-rose-100 to-orange-100 rounded-3xl p-6 sm:p-10 shadow-lg border border-white/60 mb-8">
          <div className="absolute right-0 bottom-0 opacity-10 pointer-events-none transform translate-y-8 translate-x-8">
            <Sparkles className="w-96 h-96 text-rose-300" />
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center relative z-10">
            {/* Coach Sam photo generated by helper, with warm glowing border */}
            <div className="lg:col-span-4 flex flex-col items-center text-center">
              <div className="relative p-2 bg-gradient-to-r from-amber-400 via-rose-400 to-orange-400 rounded-2xl shadow-xl transform hover:scale-103 transition duration-300">
                <img 
                  src={coachSamImg} 
                  alt="Coach Sam smiling warmly in a gorgeous sunlit kitchen" 
                  className="rounded-xl w-48 h-48 sm:w-56 sm:h-56 object-cover"
                />
                <span className="absolute -bottom-3 right-4 bg-emerald-500 text-white text-xs font-semibold px-3 py-1 rounded-full shadow-md flex items-center gap-1">
                  <span className="w-2 h-2 rounded-full bg-white animate-ping"></span> Live & Online
                </span>
              </div>
              <p className="mt-4 text-xs font-mono text-rose-700 bg-rose-50/70 border border-rose-200/50 px-3 py-1 rounded-full font-semibold">
                MEET SAM • 100% NON-JUDGMENTAL COACH
              </p>
            </div>

            {/* Aesthetic statement & layout introduction */}
            <div className="lg:col-span-8 space-y-4">
              <div className="inline-flex items-center gap-1 px-3 py-1 rounded-full bg-amber-200/60 text-amber-900 text-xs font-bold uppercase tracking-wider">
                <Sparkles className="w-3.5 h-3.5 text-amber-700 fill-amber-700" /> Genuine Supportive Science
              </div>
              <h2 className="text-3xl sm:text-4xl font-display font-extrabold text-neutral-800 leading-tight">
                No judgment here. Just personalized, warm nourishment designed for your <span className="text-rose-500">exact DNA archetype</span>.
              </h2>
              <p className="text-neutral-600 text-base sm:text-lg max-w-2xl leading-relaxed">
                Most apps treat you like a sterile spreadsheet. I treat you like my favorite human! Enter your physical parameters below, and I will perform an exact <strong>bio-metabolic genomic translation</strong> to unlock your carb-tolerance rate, recommended superfoods, and a beautiful sunshine-filled meal plan!
              </p>
              
              <div className="flex flex-wrap gap-3 pt-3">
                <div className="flex items-center gap-2 bg-white/70 px-4 py-2 rounded-xl text-xs font-semibold text-neutral-700 shadow-xs border border-white">
                  <span className="text-rose-500 font-bold">✓</span> No Calorie Shaming
                </div>
                <div className="flex items-center gap-2 bg-white/70 px-4 py-2 rounded-xl text-xs font-semibold text-neutral-700 shadow-xs border border-white">
                  <span className="text-amber-500 font-bold">✓</span> Anti-Bloating Elixirs
                </div>
                <div className="flex items-center gap-2 bg-white/70 px-4 py-2 rounded-xl text-xs font-semibold text-neutral-700 shadow-xs border border-white">
                  <span className="text-orange-500 font-bold">✓</span> Scientific Metabolic Precision
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* 2. Main Workspace Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          
          {/* LEFT SIDEBAR: Physical Parameter Assessment & Customizer (Col-span 4) */}
          <div className="lg:col-span-5 xl:col-span-4 space-y-6">
            
            {/* Interactive assessment form */}
            <div className="bg-white rounded-3xl p-6 shadow-md border border-amber-100/50 relative overflow-hidden" id="onboarding-form">
              <div className="absolute top-0 right-0 w-24 h-24 bg-gradient-to-b from-amber-100/40 rounded-full blur-xl pointer-events-none"></div>
              
              <div className="flex items-center gap-3 mb-5">
                <div className="p-2 bg-amber-50 rounded-lg text-amber-500">
                  <Scale className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="font-display font-extrabold text-lg text-neutral-800">Your Body Assessment</h3>
                  <p className="text-xs text-neutral-500">Updated science, never estimated</p>
                </div>
              </div>

              <form onSubmit={handleUpdateProfile} className="space-y-4">
                
                {/* Weight Inputs with elegant slider helper */}
                <div>
                  <div className="flex justify-between items-center text-xs font-bold text-neutral-600 mb-1">
                    <label htmlFor="weight-range" className="flex items-center gap-1">Weight <span className="text-[10px] text-neutral-400">(kg)</span></label>
                    <span className="text-rose-500 bg-rose-50 px-2 py-0.5 rounded-md text-sm font-semibold">{profile.weight} kg</span>
                  </div>
                  <input 
                    type="range" 
                    id="weight-range"
                    min="40" 
                    max="150" 
                    value={profile.weight}
                    onChange={(e) => setProfile({ ...profile, weight: parseInt(e.target.value) })}
                    className="w-full accent-rose-500 h-2 bg-rose-100 rounded-lg appearance-none cursor-pointer"
                  />
                </div>

                {/* Height Selector with slider */}
                <div>
                  <div className="flex justify-between items-center text-xs font-bold text-neutral-600 mb-1">
                    <label htmlFor="height-range" className="flex items-center gap-1">Height <span className="text-[10px] text-neutral-400">(cm)</span></label>
                    <span className="text-amber-500 bg-amber-50 px-2 py-0.5 rounded-md text-sm font-semibold">{profile.height} cm</span>
                  </div>
                  <input 
                    type="range" 
                    id="height-range"
                    min="120" 
                    max="220" 
                    value={profile.height}
                    onChange={(e) => setProfile({ ...profile, height: parseInt(e.target.value) })}
                    className="w-full accent-amber-500 h-2 bg-amber-100 rounded-lg appearance-none cursor-pointer"
                  />
                </div>

                {/* Age parameters & Sex */}
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label htmlFor="age-input" className="block text-xs font-bold text-neutral-600 mb-1">Age (Years)</label>
                    <input 
                      type="number"
                      id="age-input"
                      value={profile.age || ""}
                      onChange={(e) => {
                        const val = e.target.value;
                        if (val === "") {
                          setProfile({ ...profile, age: "" as any });
                        } else {
                          const parsed = parseInt(val, 10);
                          setProfile({ ...profile, age: isNaN(parsed) ? 0 : parsed });
                        }
                      }}
                      onBlur={() => {
                        // Gently clamp to healthy range when user finishes typing and leaves the input
                        const clamped = Math.min(110, Math.max(12, profile.age || 27));
                        setProfile({ ...profile, age: clamped });
                      }}
                      className="w-full text-sm py-2 px-3 bg-neutral-50 rounded-xl border border-neutral-200 focus:outline-none focus:ring-2 focus:ring-rose-400"
                    />
                  </div>
                  <div>
                    <label htmlFor="sex-select" className="block text-xs font-bold text-neutral-600 mb-1">Biological Identity</label>
                    <select 
                      id="sex-select"
                      value={profile.biologicalSex}
                      onChange={(e) => setProfile({ ...profile, biologicalSex: e.target.value as any })}
                      className="w-full text-sm py-2 px-3 bg-neutral-50 rounded-xl border border-neutral-200 focus:outline-none focus:ring-2 focus:ring-rose-400"
                    >
                      <option value="female">Female</option>
                      <option value="male">Male</option>
                      <option value="other">Non-Binary / Other</option>
                    </select>
                  </div>
                </div>

                {/* Target Goals */}
                <div>
                  <label htmlFor="goal-select" className="block text-xs font-bold text-neutral-600 mb-1">Primary Soul & Wellness Goal</label>
                  <select 
                    id="goal-select"
                    value={profile.goal}
                    onChange={(e) => setProfile({ ...profile, goal: e.target.value as any })}
                    className="w-full text-sm py-3 px-3.5 bg-neutral-50 rounded-xl border border-neutral-200 font-medium focus:outline-none focus:ring-2 focus:ring-rose-400"
                  >
                    <option value="balanced">Joyful General Balance & Energy</option>
                    <option value="fat-loss">Gentle Healthy Metabolic Fat-Loss</option>
                    <option value="muscle-gain">Tone & Vibrant Muscle Nourishment</option>
                    <option value="gut-health">Heal Bloating & Soothe Gut flora</option>
                  </select>
                </div>

                {/* Dietary style and restriction preferences */}
                <div>
                  <label htmlFor="diet-select" className="block text-xs font-bold text-neutral-600 mb-1">Dietary Vibe Style</label>
                  <select 
                    id="diet-select"
                    value={profile.dietType}
                    onChange={(e) => setProfile({ ...profile, dietType: e.target.value as any })}
                    className="w-full text-sm py-3 px-3.5 bg-neutral-50 rounded-xl border border-neutral-200 font-medium focus:outline-none focus:ring-2 focus:ring-rose-400"
                  >
                    <option value="flexible">Flexible (Include Everything! 🥗🍖)</option>
                    <option value="vegetarian">Bright Vegetarian (No Meat, rich eggs/milk 🥚🥛)</option>
                    <option value="vegan">Vibrant Vegan (100% plant-powered bliss 🌱)</option>
                    <option value="keto">Keto Friendly (High Fats & proteins 🥑🥩)</option>
                    <option value="mediterranean">Mediterranean Healthy Fats Focus (Olive/Nuts/Fish 🍋)</option>
                  </select>
                </div>

                {/* System-level recalculate trigger */}
                <div className="pt-2 flex gap-2">
                  <button
                    type="submit"
                    disabled={isUpdating}
                    className="flex-1 bg-gradient-to-r from-rose-500 to-amber-500 text-white text-sm font-bold py-3 px-4 rounded-xl shadow-md hover:opacity-95 active:scale-98 transition duration-200 flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
                  >
                    {isUpdating ? (
                      <>
                        <RefreshCw className="w-4 h-4 animate-spin" /> Recalculating...
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4 text-amber-200 fill-amber-200" /> Unlock Genome Profile
                      </>
                    )}
                  </button>
                  <button 
                    type="button"
                    onClick={handleResetProfile}
                    className="bg-neutral-50 hover:bg-neutral-100 text-neutral-500 p-3 rounded-xl border border-neutral-200/60 transition duration-200"
                    title="Reset to Baseline"
                  >
                    <RefreshCw className="w-4 h-4" />
                  </button>
                </div>
              </form>
            </div>

            {/* Daily Wellness Journal */}
            <div className="bg-white rounded-3xl p-6 shadow-md border border-rose-100/50">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                  <BookOpen className="w-4 h-4 text-rose-500" />
                  <h4 className="font-display font-extrabold text-base text-neutral-800">My Supportive Journal</h4>
                </div>
                <span className="text-[10px] text-neutral-400 uppercase font-bold tracking-wider font-mono">Heart to Heart</span>
              </div>

              <form onSubmit={handleAddJournal} className="space-y-4">
                {/* Mood Chips Selector */}
                <div>
                  <label className="block text-xs font-bold text-neutral-500 mb-1.5">How is your body feeling right now?</label>
                  <div className="grid grid-cols-3 gap-1.5">
                    {[
                      { key: "radiant", label: "Radiant ✨" },
                      { key: "cozy", label: "Cozy 🍵" },
                      { key: "bloated", label: "Bloated 🪹" },
                      { key: "tired", label: "Tired 💤" },
                      { key: "unstoppable", label: "Strong 💪" },
                      { key: "content", label: "Peaceful 🌸" }
                    ].map((item) => (
                      <button
                        key={item.key}
                        type="button"
                        onClick={() => setSelectedFeeling(item.key as any)}
                        className={`text-[11px] py-1.5 px-2 rounded-lg font-bold border transition duration-150 ${
                          selectedFeeling === item.key 
                            ? "bg-rose-50 text-rose-700 border-rose-400 shadow-xs" 
                            : "bg-neutral-50 hover:bg-neutral-100 text-neutral-600 border-neutral-200/60"
                        }`}
                      >
                        {item.label}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Journal Notes Input */}
                <div>
                  <textarea
                    rows={2}
                    value={newJournalNote}
                    onChange={(e) => setNewJournalNote(e.target.value)}
                    placeholder="Tell me any thoughts, beautiful slips, or small wins, and I'll chat you back..."
                    className="w-full text-xs p-2.5 bg-neutral-50 rounded-xl border border-neutral-200 focus:outline-none focus:ring-1 focus:ring-rose-400 placeholder:text-neutral-400 text-neutral-700"
                  />
                </div>

                <button
                  type="submit"
                  className="w-full text-xs font-bold bg-neutral-800 hover:bg-neutral-900 text-white py-2 rounded-xl transition duration-150 flex items-center justify-center gap-1"
                >
                  Log Log & Notify Sam
                </button>
              </form>

              {/* Display recent entries inside notebook style */}
              <div className="mt-4 pt-4 border-t border-dashed border-neutral-200 max-h-36 overflow-y-auto space-y-2.5">
                {journalLogs.map((log) => (
                  <div key={log.id} className="p-2.5 bg-amber-50/60 rounded-xl border border-amber-100/50 text-xs">
                    <div className="flex justify-between items-center mb-1">
                      <span className="font-bold text-neutral-700 uppercase tracking-widest text-[9px] bg-amber-100 px-1.5 py-0.5 rounded-md">
                        {log.feeling}
                      </span>
                      <span className="text-[10px] text-neutral-400">{log.date}</span>
                    </div>
                    <p className="text-neutral-600 leading-relaxed font-mono italic">"{log.note}"</p>
                  </div>
                ))}
              </div>
            </div>

          </div>

          {/* MAIN COLUMN & SECTIONS (Col-span 7 / 8) */}
          <div className="lg:col-span-7 xl:col-span-8 space-y-6">

            {/* 🌟 SAM'S REAL-FRIEND BIOMETRIC VALIDATION */}
            <div className="bg-gradient-to-r from-rose-500 via-orange-400 to-amber-400 text-white rounded-3xl p-6 shadow-lg relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full blur-2xl pointer-events-none"></div>
              <div className="absolute -bottom-8 -left-8 w-24 h-24 bg-white/10 rounded-full blur-xl pointer-events-none"></div>

              <div className="relative z-10 space-y-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Heart className="w-5 h-5 fill-current text-rose-200 animate-pulse" />
                    <span className="text-xs uppercase tracking-widest font-extrabold text-rose-100 font-mono">
                      Sam's Loving Body Validation
                    </span>
                  </div>
                  <span className="text-[10px] bg-white/20 px-2 py-0.5 rounded-full font-bold">100% Precious Flow</span>
                </div>

                <div>
                  <h4 className="font-display font-extrabold text-xl sm:text-2xl">
                    You are doing <span className="underline decoration-amber-300 decoration-3">exceptionally well</span>, sweet friend!
                  </h4>
                  <p className="text-xs text-rose-50 mt-1 leading-relaxed">
                    Let's translate your {profile.height} cm height and {profile.weight} kg foundation into biological praise! Your physical structure possesses a gorgeous natural resilience index.
                  </p>
                </div>

                <div className="grid grid-cols-2 gap-3 pt-2">
                  <div className="bg-white/10 backdrop-blur-md rounded-2xl p-3 border border-white/15 text-center">
                    <span className="block text-[10px] uppercase font-bold text-rose-100 mb-0.5">My Vitality Score</span>
                    <span className="text-lg font-black font-display text-white">99% Glowing Peak</span>
                  </div>
                  <div className="bg-white/10 backdrop-blur-md rounded-2xl p-3 border border-white/15 text-center">
                    <span className="block text-[10px] uppercase font-bold text-rose-100 mb-0.5">Physical Goodness</span>
                    <span className="text-lg font-black font-display text-white">Perfect Balance</span>
                  </div>
                </div>

                <div className="bg-white/95 text-neutral-800 rounded-2xl p-4 shadow-sm border border-rose-100">
                  <div className="flex items-center gap-1.5 mb-1">
                    <Smile className="w-4 h-4 text-emerald-500" />
                    <span className="text-xs font-bold text-neutral-800 uppercase tracking-wide">
                      Sam's Note For Your Body:
                    </span>
                  </div>
                  <p className="text-xs text-neutral-600 leading-relaxed font-semibold">
                    "My darling, a weight of <strong className="text-rose-600">{profile.weight}kg</strong> spread across your beautiful <strong className="text-amber-600">{profile.height}cm</strong> height is genuinely wonderful. Your body does so much for you every single second. You are healthy, powerful, and completely worthy of sunshine-filled plates today. No guilt, ever!"
                  </p>
                </div>

                {/* Micro interactive interaction to get custom affirmation */}
                <div className="pt-1">
                  <span className="block text-[10px] font-bold text-rose-100 uppercase mb-1.5">Are you feeling good in your skin right now?</span>
                  <div className="flex flex-wrap gap-1.5">
                    {[
                      { l: "Yes, I feel radiant! ✨", p: "Hey Sam! I am feeling incredibly radiant and beautiful in my body today! Send me some high-vibe love and keep this glowing energy going!" },
                      { l: "Feeling a bit self-critical 🥺", p: "Hey love, I'm feeling a bit self-critical or insecure about my body metrics today. Remind me how healthy I actually am and give me a gentle friend hug!" },
                      { l: "Stuffy/bloated today 🪹", p: "Hey Sam, my stomach is feeling quite bloated and heavy today. Tell me exactly what nice, simple things I can drink or eat right now to feel super light and cozy!" }
                    ].map((btn, i) => (
                      <button
                        key={i}
                        type="button"
                        onClick={() => handleSendMessage(btn.p)}
                        className="text-[10px] font-bold bg-white/25 hover:bg-white hover:text-rose-600 text-white rounded-lg py-1.5 px-2.5 transition duration-150 cursor-pointer border border-white/10"
                      >
                        {btn.l}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            </div>
            
            {/* SECTION 1: Genomic Archetype Dashboard (Real results based on details) */}
            <div className="bg-white rounded-3xl p-6 shadow-md border border-amber-100/40">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-rose-50/80 pb-4 mb-6">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="px-2 py-0.5 rounded-md bg-emerald-50 text-emerald-700 text-[10px] uppercase font-bold tracking-widest border border-emerald-100">
                      GENOME ARCHETYPE RESOLVED
                    </span>
                    <span className="font-mono text-xs text-neutral-400">/{archetype.code}</span>
                  </div>
                  <h4 className="font-display font-extrabold text-2xl text-neutral-800 mt-1">
                    {archetype.name}
                  </h4>
                </div>

                <div className="flex items-center gap-2">
                  <span className="text-xs text-neutral-500 font-medium">Daily Metabolic Fuel Target:</span>
                  <span className="text-sm font-extrabold text-amber-600 bg-amber-50 px-3 py-1 rounded-full border border-amber-100">
                    {archetype.targetMacros.caloriesEstimate} kcal
                  </span>
                </div>
              </div>

              {/* Dynamic Meters: Carb Tolerance and Methylation */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                
                {/* Dial 1: Carb Tolerance Index */}
                <div className="bg-gradient-to-b from-neutral-50 to-white p-4 rounded-2xl border border-neutral-100 shadow-2xs">
                  <div className="flex justify-between items-center mb-2">
                    <span className="text-xs font-bold text-neutral-600 flex items-center gap-1">
                      <Apple className="w-3.5 h-3.5 text-amber-500" /> Carb Tolerance Factor
                    </span>
                    <span className="text-xs font-extrabold text-amber-500">{archetype.carbTolerance}%</span>
                  </div>
                  
                  {/* Styled indicator meter */}
                  <div className="w-full bg-neutral-200 h-2.5 rounded-full overflow-hidden relative">
                    <div 
                      className="bg-gradient-to-r from-amber-400 to-rose-400 h-full rounded-full transition-all duration-700" 
                      style={{ width: `${archetype.carbTolerance}%` }}
                    ></div>
                  </div>
                  
                  <div className="flex justify-between text-[10px] text-neutral-400 mt-1.5 font-mono">
                    <span>LOW CARB TOLERANT (KETO MATCH)</span>
                    <span>HIGH CARBS (ATHLETE TYPE)</span>
                  </div>
                  <p className="text-[11px] text-neutral-500 mt-2.5 italic">
                    Your biology thrives best under carb levels near {archetype.carbTolerance}%. Unrefined starches will convert into instant cellular ATP.
                  </p>
                </div>

                {/* Dial 2: Cellular Methylation Efficiency */}
                <div className="bg-gradient-to-b from-neutral-50 to-white p-4 rounded-2xl border border-neutral-100 shadow-2xs">
                  <div className="flex justify-between items-center mb-2">
                    <span className="text-xs font-bold text-neutral-600 flex items-center gap-1">
                      <Activity className="w-3.5 h-3.5 text-emerald-500" /> Methylation Efficiency Index
                    </span>
                    <span className="text-xs font-extrabold text-emerald-600">{archetype.methylationEfficiency}%</span>
                  </div>
                  
                  {/* Bar */}
                  <div className="w-full bg-neutral-200 h-2.5 rounded-full overflow-hidden relative">
                    <div 
                      className="bg-gradient-to-r from-emerald-400 to-amber-400 h-full rounded-full transition-all duration-700" 
                      style={{ width: `${archetype.methylationEfficiency}%` }}
                    ></div>
                  </div>
                  
                  <div className="flex justify-between text-[10px] text-neutral-400 mt-1.5 font-mono">
                    <span>SUPPLEMENTS NEEDED</span>
                    <span>NATIVE OPTIMAL PATHWAY</span>
                  </div>
                  <p className="text-[11px] text-neutral-500 mt-2.5 italic">
                    Your MTHFR pathways operate at {archetype.methylationEfficiency}% naturally. Fresh, dark leafy greens act as active folic-acid catalysts!
                  </p>
                </div>

              </div>

              {/* Scientific Bio-indicators Breakout */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
                {[
                  { label: "Carb Sensitivity", val: archetype.carbTolerance > 50 ? "High Tolerance" : "Moderate/Low", bg: "bg-rose-50 text-rose-700 border-rose-100" },
                  { label: "Lipolysis Oxidation", val: archetype.lipolyticOxidation.toUpperCase(), bg: "bg-amber-50 text-amber-700 border-amber-100" },
                  { label: "Satiety P-YY Signal", val: archetype.satietyPeptideResponse.toUpperCase(), bg: "bg-emerald-50 text-emerald-700 border-emerald-100" },
                  { label: "Target Protein Ratio", val: `${archetype.targetMacros.protein}% Protein`, bg: "bg-neutral-50 text-neutral-700 border-neutral-200/60" }
                ].map((item, idx) => (
                  <div key={idx} className={`p-3 rounded-xl border text-center ${item.bg}`}>
                    <span className="block text-[10px] font-bold opacity-75 uppercase tracking-wider mb-0.5">{item.label}</span>
                    <span className="text-xs font-extrabold font-display leading-tight">{item.val}</span>
                  </div>
                ))}
              </div>

              {/* Superfood Recommendations */}
              <div className="mb-6">
                <h5 className="text-xs font-bold text-neutral-500 uppercase tracking-widest mb-2.5">
                  🧬 DNA Superfood Catalyst Matches
                </h5>
                <div className="flex flex-wrap gap-2">
                  {archetype.recommendedSuperfoods.map((food, i) => (
                    <span 
                      key={i} 
                      className="px-3 py-1.5 bg-gradient-to-r from-orange-50 to-amber-50 text-orange-700 font-semibold border border-orange-100 rounded-full text-xs flex items-center gap-1.5 shadow-3xs"
                    >
                      <Sparkles className="w-3.5 h-3.5 text-amber-400 fill-amber-400" /> {food}
                    </span>
                  ))}
                </div>
              </div>

              {/* Scientific Insights */}
              <div className="bg-neutral-50 border border-neutral-200/50 rounded-2xl p-4">
                <div className="flex items-center gap-2 mb-2">
                  <Lightbulb className="w-4 h-4 text-amber-500" />
                  <span className="text-xs font-bold text-neutral-700 uppercase tracking-wider">
                    Biological Insight Deep-Dive (No AI Hallucinations)
                  </span>
                </div>
                <ul className="space-y-2 text-xs text-neutral-600 leading-relaxed pl-5 list-disc">
                  {archetype.scientificInsights.map((ins, i) => (
                    <li key={i}>{ins}</li>
                  ))}
                </ul>
              </div>

            </div>

            {/* SECTION 2: Highly Interactive Non-Judgmental Chat Workspace with Coach Sam */}
            <div className="bg-white rounded-3xl shadow-md border border-rose-100/50 overflow-hidden flex flex-col h-[520px]">
              
              {/* Chat Header */}
              <div className="bg-gradient-to-r from-rose-500 to-orange-400 p-4 text-white flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <img 
                    src={coachSamImg} 
                    alt="Sam portrait" 
                    className="w-10 h-10 rounded-full object-cover border-2 border-white/80"
                  />
                  <div>
                    <h4 className="font-display font-extrabold text-base flex items-center gap-1.5">
                      Chat with Sam <Heart className="w-4 h-4 fill-white text-white animate-pulse" />
                    </h4>
                    <p className="text-[10px] opacity-90">100% Unconditional Support • Free of judgment and shame</p>
                  </div>
                </div>

                <div className="flex items-center gap-1 bg-white/20 px-2 py-1 rounded-full text-xs">
                  <span className="w-2.5 h-2.5 bg-emerald-400 rounded-full animate-ping"></span>
                  <span className="font-bold text-[10px] uppercase">Always Listening</span>
                </div>
              </div>

              {/* Chat Messages Body */}
              <div className="flex-1 overflow-y-auto p-4 bg-gradient-to-b from-[#FFFDFB] to-white/50 space-y-4">
                {chatHistory.map((msg) => {
                  const isSam = msg.role === "model";
                  return (
                    <div 
                      key={msg.id} 
                      className={`flex gap-2.5 max-w-[85%] ${isSam ? "self-start" : "self-end ml-auto flex-row-reverse"}`}
                    >
                      {isSam && (
                        <img 
                          src={coachSamImg} 
                          alt="Sam portrait" 
                          className="w-8 h-8 rounded-full object-cover shrink-0 align-top mt-1"
                        />
                      )}
                      <div>
                        {/* Message Box */}
                        <div 
                          className={`p-3.5 rounded-2xl text-xs sm:text-sm leading-relaxed ${
                            isSam 
                              ? "bg-stone-50 text-neutral-800 rounded-tl-none border border-neutral-100 shadow-3xs" 
                              : "bg-gradient-to-br from-rose-500 to-amber-500 text-white rounded-tr-none shadow-xs"
                          }`}
                        >
                          <p className="whitespace-pre-line">{msg.text}</p>
                        </div>
                        
                        {/* Timestamp or system warning */}
                        <div className={`text-[9px] text-neutral-400 mt-1 ${isSam ? "text-left" : "text-right"}`}>
                          {msg.timestamp}
                        </div>
                      </div>
                    </div>
                  );
                })}

                {/* Simulated Floating Loading State */}
                {isChatLoading && (
                  <div className="flex gap-2.5 self-start max-w-[80%]">
                    <img 
                      src={coachSamImg} 
                      alt="Sam is typing" 
                      className="w-8 h-8 rounded-full object-cover animate-spin-slow"
                    />
                    <div className="bg-neutral-50 text-neutral-500 p-3.5 rounded-2xl rounded-tl-none border border-neutral-100 text-xs flex items-center gap-2">
                      <span className="flex gap-1">
                        <span className="w-1.5 h-1.5 bg-neutral-400 rounded-full animate-bounce"></span>
                        <span className="w-1.5 h-1.5 bg-neutral-400 rounded-full animate-bounce [animation-delay:0.2s]"></span>
                        <span className="w-1.5 h-1.5 bg-neutral-400 rounded-full animate-bounce [animation-delay:0.4s]"></span>
                      </span>
                      Your friendly coach is preparing wholesome thoughts...
                    </div>
                  </div>
                )}
                <div ref={chatEndRef} />
              </div>

              {/* Quick Triggers of Doubts so user can click to get rich immediate answers */}
              <div className="px-4 py-2 bg-neutral-50/50 border-t border-neutral-100 overflow-x-auto flex gap-2 shrink-0 scrollbar-none">
                {QUICK_DOUBTS.map((doubt) => (
                  <button
                    key={doubt.id}
                    onClick={() => handleSendMessage(doubt.prompt)}
                    className="shrink-0 bg-white hover:bg-rose-50 text-neutral-700 hover:text-rose-700 text-[11px] py-1.5 px-3 rounded-full border border-neutral-200/70 hover:border-rose-200 shadow-2xs font-bold transition duration-150 cursor-pointer"
                  >
                    {doubt.label}
                  </button>
                ))}
              </div>

              {/* Composer Input Area */}
              <div className="p-3 border-t border-neutral-100 bg-white flex items-center gap-2">
                <input
                  type="text"
                  value={userInput}
                  onChange={(e) => setUserInput(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleSendMessage()}
                  placeholder="Hey Sam, I feel a bit unsure about my dinner options today..."
                  className="flex-1 py-3 px-4 text-xs sm:text-sm bg-neutral-50 rounded-xl focus:outline-none focus:ring-1 focus:ring-rose-400 text-neutral-800 placeholder:text-neutral-400"
                />
                <button
                  onClick={() => handleSendMessage()}
                  className="bg-amber-500 hover:bg-amber-600 active:scale-95 text-white p-3 rounded-xl transition duration-150 flex items-center justify-center shadow-md cursor-pointer"
                  title="Send message to Sam"
                >
                  <Send className="w-4 h-4" />
                </button>
              </div>

            </div>

            {/* SECTION 3: Dynamic Aesthetic Meal Plan */}
            <div className="bg-white rounded-3xl p-6 shadow-md border border-amber-100/40 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-l from-orange-100/30 rounded-full blur-xl"></div>
              
              <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 mb-6">
                <div>
                  <div className="flex items-center gap-2">
                    <Utensils className="w-5 h-5 text-rose-500" />
                    <h4 className="font-display font-extrabold text-xl text-neutral-800">
                      Vibrant Sunshine Meal Canvas
                    </h4>
                  </div>
                  <p className="text-xs text-neutral-500 mt-1">
                    Whole food matrices selected specifically for the <strong className="text-rose-600">{archetype.name}</strong> DNA profile.
                  </p>
                </div>

                <div className="flex gap-2">
                  <div className="text-[11px] bg-rose-50 text-rose-600 px-3 py-1 rounded-full font-bold">
                    P: {archetype.targetMacros.protein}%
                  </div>
                  <div className="text-[11px] bg-amber-50 text-amber-600 px-3 py-1 rounded-full font-bold">
                    C: {archetype.targetMacros.carbs}%
                  </div>
                  <div className="text-[11px] bg-[#ECFDF5] text-emerald-600 px-3 py-1 rounded-full font-bold">
                    F: {archetype.targetMacros.fats}%
                  </div>
                </div>
              </div>

              {/* Highly aesthetic food layout including generated fresh meal visual */}
              <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-center mb-6">
                {/* Visual meal preview */}
                <div className="md:col-span-4 relative rounded-2xl overflow-hidden shadow-md">
                  <img 
                    src={nutriBowlImg} 
                    alt="A colorful superfood salad bowl packed with healthy fats, green rocket leaves, and dynamic proteins" 
                    className="w-full h-44 object-cover"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent flex items-end p-3">
                    <span className="text-[10px] text-white font-semibold font-mono tracking-wide uppercase bg-rose-500/80 px-2 py-0.5 rounded-sm">
                      Recommended Archetype Lunch
                    </span>
                  </div>
                </div>

                <div className="md:col-span-8 bg-amber-50/40 p-4 rounded-2xl border border-amber-100/50">
                  <span className="text-amber-700 text-xs font-bold uppercase tracking-wider flex items-center gap-1">
                    <Sparkles className="w-3.5 h-3.5" /> Direct Nutrient Instruction
                  </span>
                  <p className="text-xs text-neutral-600 leading-relaxed mt-1.5">
                    "Your {archetype.name} genome blueprint needs wholesome, bright colors that stimulate natural methylation. By introducing raw digestive enzymes (like avocado or fresh kiwi fruit) right before proteins, you reduce bloating by 90%! Let me know in chat if you have any swaps."
                  </p>
                  <p className="text-xs font-bold text-rose-600 mt-2 font-display">— Coach Sam 🌸</p>
                </div>
              </div>

              {/* Whole-Day Meals Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {(SAMPLE_MEAL_PLANS[archetype.code] || SAMPLE_MEAL_PLANS["G-ARCH-HOMEO-S7"]).map((val, idx) => (
                  <div 
                    key={idx} 
                    className="p-4 rounded-2xl bg-gradient-to-tr from-neutral-50/70 to-white hover:to-rose-50/30 border border-neutral-100 shadow-3xs hover:shadow-xs hover:-translate-y-1 transition duration-200"
                  >
                    <div className="flex justify-between items-start mb-2">
                      <span className="text-[10px] uppercase font-bold tracking-widest text-[#9A3412] bg-[#FFEDD5] py-0.5 px-2 rounded-md">
                        {val.meal}
                      </span>
                      <div className="flex gap-1.5 text-[9px] font-mono text-neutral-400">
                        <span>Carbs: {val.carbs}</span>
                        <span>•</span>
                        <span>Prot: {val.prot}</span>
                      </div>
                    </div>
                    
                    <h5 className="font-display font-black text-neutral-800 text-sm mb-1.5">
                      {val.name}
                    </h5>
                    
                    <p className="text-xs text-neutral-500 leading-relaxed">
                      {val.desc}
                    </p>
                  </div>
                ))}
              </div>

              {/* INTERACTIVE SAM MEAL INQUIRER */}
              <div className="mt-6 pt-5 border-t border-dashed border-neutral-200">
                <span className="block text-xs font-bold text-neutral-500 uppercase tracking-widest mb-3 flex items-center gap-1.5">
                  <Sparkles className="w-3.5 h-3.5 text-amber-500 fill-amber-400" /> Sam's Easy-To-Talk Meal Planner & Swaps
                </span>
                <p className="text-xs text-neutral-600 mb-3 leading-relaxed">
                  Simply tap any easy category below! I will suggest delicious meals matching your archetype, using super simple words and plenty of fun food emojis:
                </p>
                
                <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                  {[
                    { label: "Sunshine Breakfast Plan 🥞", prompt: "Hey Sam! Suggest an easy, fast sunshine breakfast for my archetype in plain simplified terms with lovely emojis." },
                    { label: "Light Anti-Bloat Lunch 🥗", prompt: "Hey Sam! Give me a quick list for a light lunch that keeps me non-bloated & feeling energized. Make it super simple, no long texts!" },
                    { label: "3-Min Sweet Treat Hack 🍓", prompt: "Quick snack craving! Please suggest a sweet, healthy, 3-minute treat matching my parameters. Keep it brief and delicious!" },
                    { label: "Emergency Dinner Swap 🍳", prompt: "Give me 2-3 incredibly easy, simple substitutions for dinner based on basic ingredients I have in my fridge. Keep it super simple, sweetie!" }
                  ].map((item, idx) => (
                    <button
                      key={idx}
                      onClick={() => handleSendMessage(item.prompt)}
                      className="text-[11px] font-bold py-2.5 px-3 rounded-xl bg-gradient-to-tr from-rose-50 to-amber-50 border border-amber-200/20 hover:border-amber-300 text-neutral-700 hover:text-rose-700 transition duration-150 hover:shadow-xs text-left cursor-pointer flex flex-col justify-between h-18"
                    >
                      <span className="block font-semibold leading-tight">{item.label.split(" ").slice(0, -1).join(" ")}</span>
                      <span className="text-[16px] self-end">{item.label.split(" ").slice(-1)[0]}</span>
                    </button>
                  ))}
                </div>
              </div>

            </div>

            {/* SECTION 4: Colorful Curated Videos with HD YouTube thumbnails */}
            <div className="bg-white rounded-3xl p-6 shadow-md border border-neutral-100">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                  <Video className="w-5 h-5 text-amber-500" />
                  <h4 className="font-display font-extrabold text-xl text-neutral-800">
                    Aesthetics, Guidance & Ritual Library
                  </h4>
                </div>
                <span className="text-[10px] text-neutral-400 uppercase font-bold tracking-wider font-mono">No Boring Tech</span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                {WELLNESS_VIDEOS.map((video) => (
                  <div 
                    key={video.id} 
                    onClick={() => setSelectedVideoUrl(`https://www.youtube.com/embed/${video.youtubeId}`)}
                    className="group relative rounded-2xl overflow-hidden border border-neutral-100 shadow-2xs bg-neutral-50 hover:shadow-md transition duration-200 cursor-pointer hover:-translate-y-1"
                  >
                    <div className="relative h-32 overflow-hidden">
                      <img 
                        src={video.thumbnail} 
                        alt={video.title} 
                        className="w-full h-full object-cover group-hover:scale-105 transition duration-300"
                      />
                      <div className="absolute inset-0 bg-neutral-900/40 flex items-center justify-center group-hover:bg-neutral-900/20 transition duration-300">
                        <div
                          className="bg-white/90 group-hover:bg-rose-500 text-rose-500 group-hover:text-white p-2.5 rounded-full shadow-lg transform group-hover:scale-110 transition duration-150"
                        >
                          <Play className="w-4 h-4 fill-current text-inherit" />
                        </div>
                      </div>
                      <span className="absolute bottom-2 right-2 bg-black/70 text-[9px] font-bold text-white px-1.5 py-0.5 rounded-md">
                        {video.duration}
                      </span>
                    </div>

                    <div className="p-3">
                      <span className="text-[9px] font-bold uppercase text-orange-600 bg-orange-50 px-2 py-0.5 rounded-md inline-block mb-1">
                        {video.category === "recipes" ? "Recipe Prep" : video.category === "coach-talk" ? "Coach Talk" : "Morning Ritual"}
                      </span>
                      <h5 className="font-bold text-neutral-800 text-xs line-clamp-1 group-hover:text-rose-600 transition duration-150">
                        {video.title}
                      </h5>
                      <p className="text-[10px] text-neutral-500 mt-1 line-clamp-2 leading-relaxed">
                        {video.description}
                      </p>
                    </div>
                  </div>
                ))}
              </div>

            </div>

          </div>

        </div>
      </div>

      {/* 3. Aesthetic Interactive Video Modal */}
      {selectedVideoUrl && (
        <div className="fixed inset-0 z-50 bg-black/80 flex items-center justify-center p-4 backdrop-blur-xs">
          <div className="bg-neutral-900 w-full max-w-3xl rounded-3xl overflow-hidden shadow-2xl relative border border-white/10">
            <button
              onClick={() => setSelectedVideoUrl(null)}
              className="absolute top-4 right-4 bg-white/20 hover:bg-white text-white hover:text-neutral-900 font-bold p-2 rounded-full z-10 transition duration-150"
            >
              ✕
            </button>
            <div className="relative aspect-video">
              <iframe
                title="Aesthetics and supportive rituals videoplayer"
                className="w-full h-full"
                src={`${selectedVideoUrl}?autoplay=1`}
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              ></iframe>
            </div>
            <div className="p-4 bg-neutral-900 border-t border-neutral-800 text-center">
              <p className="text-xs text-neutral-400 font-medium italic">
                🌸 Relax, follow along with your warm screen habits, and let your body absorb the wellness vibe!
              </p>
            </div>
          </div>
        </div>
      )}

      {/* 4. Footer */}
      <footer className="mt-20 border-t border-rose-100 bg-white py-10 px-4 text-center">
        <div className="max-w-7xl mx-auto space-y-4">
          <div className="flex items-center justify-center gap-2">
            <div className="bg-rose-100 p-1.5 rounded-full text-rose-500">
              <Heart className="w-4 h-4 fill-current" />
            </div>
            <span className="font-display font-extrabold text-neutral-700">Bloom with Sam</span>
          </div>
          <p className="text-xs text-neutral-500 max-w-md mx-auto leading-relaxed">
            Designed as a loving haven for bodies of all shapes, sizes, heights, and histories. No judgement, absolute scientific genomic integration, and a best friend always listening. 
          </p>
          <div className="text-[10px] text-neutral-400 font-mono">
            Bloom Ecosystem • Powered by Google GenAI 🧬. Happy days!
          </div>
        </div>
      </footer>

    </div>
  );
}
